In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as matlab

In [2]:
dataset=pd.read_csv("preprocessed_data.csv")
dataset

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes
0,100083,0,0,103500.0,573628.5,24435.0,463500.0,0.009657,-15406,-892,...,0,0,0,0,0,0,0,1,0,0
1,100145,0,1,202500.0,260725.5,16789.5,198000.0,0.018850,-16282,-4375,...,1,0,0,0,0,0,1,0,0,0
2,100165,0,0,175500.0,1293502.5,35568.0,1129500.0,0.018850,-21961,365243,...,0,0,0,0,0,0,1,0,0,0
3,100179,0,0,202500.0,675000.0,53329.5,675000.0,0.031329,-11375,-2311,...,0,0,0,0,1,0,0,0,0,0
4,100190,0,0,162000.0,263686.5,24781.5,238500.0,0.022625,-13972,-4472,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11346,456084,0,1,99000.0,675000.0,21906.0,675000.0,0.020246,-14007,-2021,...,0,0,0,0,0,0,1,0,0,0
11347,456088,1,0,29250.0,663093.0,21519.0,553500.0,0.031329,-20086,365243,...,0,0,0,0,0,0,0,1,0,0
11348,456140,1,1,261000.0,711454.5,47673.0,643500.0,0.018850,-11407,-1641,...,0,0,0,0,0,0,1,0,0,0
11349,456195,0,0,94500.0,270000.0,15075.0,270000.0,0.028663,-20246,-5452,...,0,0,0,0,0,0,0,1,0,0
11350,456226,0,0,225000.0,500566.5,34969.5,472500.0,0.031329,-14106,-226,...,0,0,0,0,0,0,0,0,0,0

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes
0,100083,0,0,103500.0,573628.5,24435.0,463500.0,0.009657,-15406,-892,...,0,0,0,0,0,0,0,1,0,0
1,100145,0,1,202500.0,260725.5,16789.5,198000.0,0.018850,-16282,-4375,...,1,0,0,0,0,0,1,0,0,0
2,100165,0,0,175500.0,1293502.5,35568.0,1129500.0,0.018850,-21961,365243,...,0,0,0,0,0,0,1,0,0,0
3,100179,0,0,202500.0,675000.0,53329.5,675000.0,0.031329,-11375,-2311,...,0,0,0,0,1,0,0,0,0,0
4,100190,0,0,162000.0,263686.5,24781.5,238500.0,0.022625,-13972,-4472,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11346,456084,0,1,99000.0,675000.0,21906.0,675000.0,0.020246,-14007,-2021,...,0,0,0,0,0,0,1,0,0,0
11347,456088,1,0,29250.0,663093.0,21519.0,553500.0,0.031329,-20086,365243,...,0,0,0,0,0,0,0,1,0,0
11348,456140,1,1,261000.0,711454.5,47673.0,643500.0,0.018850,-11407,-1641,...,0,0,0,0,0,0,1,0,0,0
11349,456195,0,0,94500.0,270000.0,15075.0,270000.0,0.028663,-20246,-5452,...,0,0,0,0,0,0,0,1,0,0
11350,456226,0,0,225000.0,500566.5,34969.5,472500.0,0.031329,-14106,-226,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dataset.columns

Index(['SK_ID_CURR', 'TARGET', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       ...
       'FONDKAPREMONT_MODE_reg oper spec account',
       'HOUSETYPE_MODE_specific housing', 'HOUSETYPE_MODE_terraced house',
       'WALLSMATERIAL_MODE_Mixed', 'WALLSMATERIAL_MODE_Monolithic',
       'WALLSMATERIAL_MODE_Others', 'WALLSMATERIAL_MODE_Panel',
       'WALLSMATERIAL_MODE_Stone, brick', 'WALLSMATERIAL_MODE_Wooden',
       'EMERGENCYSTATE_MODE_Yes'],
      dtype='object', length=230)

In [5]:
dataset["TARGET"].value_counts()

0    10666
1      685
Name: TARGET, dtype: int64

In [7]:
independent=dataset[['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'FONDKAPREMONT_MODE_reg oper spec account',
       'HOUSETYPE_MODE_specific housing', 'HOUSETYPE_MODE_terraced house',
       'WALLSMATERIAL_MODE_Mixed', 'WALLSMATERIAL_MODE_Monolithic',
       'WALLSMATERIAL_MODE_Others', 'WALLSMATERIAL_MODE_Panel',
       'WALLSMATERIAL_MODE_Stone, brick', 'WALLSMATERIAL_MODE_Wooden',
       'EMERGENCYSTATE_MODE_Yes']]
independent
dependent=dataset[['TARGET']]

In [8]:
independent.shape

(11351, 19)

In [9]:
dependent

       TARGET
0           0
1           0
2           0
3           0
4           0
...       ...
11346       0
11347       1
11348       1
11349       0
11350       0

[11351 rows x 1 columns]

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],'max_features':['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
#fitting the model for grid search
grid.fit(X_train,Y_train)

C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.

Fitting 3 folds for each of 12 candidates, totalling 36 fits

[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:   13.4s
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:   13.8s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [14]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [15]:
y_pred=classifier.predict(X_test)

In [16]:
re=grid.cv_results_
grid_predictions=grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_pred)

In [17]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
print(cm)

[[3348  205]
 [ 218   13]]

In [19]:
from sklearn.metrics import classification_report
clf_report=classification_report(Y_test,y_pred)

In [20]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      3553
           1       0.06      0.06      0.06       231

    accuracy                           0.89      3784
   macro avg       0.50      0.50      0.50      3784
weighted avg       0.89      0.89      0.89      3784

In [21]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.5074919920121159

In [24]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.062507,0.012759,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.887555,0.884808,0.884949,0.885771,0.001263,9
1,0.046880,0.000002,0.005209,0.007366,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.884836,0.883838,0.887562,0.885412,0.001574,10
2,0.057295,0.007363,0.010416,0.007365,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.882171,0.885282,0.888642,0.885365,0.002642,11
3,0.036459,0.007365,0.010420,0.007368,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.886052,0.887063,0.887289,0.886801,0.000538,5
4,0.067714,0.007368,0.010416,0.007366,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.889796,0.882059,0.887835,0.886564,0.003284,8
5,0.026046,0.007370,0.015624,0.000002,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.884091,0.891085,0.884751,0.886642,0.003153,7
6,0.067712,0.007370,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.882202,0.883064,0.888057,0.884441,0.002581,12
7,0.031246,0.000003,0.015630,0.000003,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.879738,0.888977,0.891285,0.886666,0.004990,6
8,0.067712,0.007363,0.005210,0.007367,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.891373,0.881931,0.888977,0.887428,0.004007,3
9,0.036461,0.007365,0.010417,0.007366,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.889695,0.889760,0.889077,0.889511,0.000308,1
10,0.072919,0.007365,0.010421,0.007369,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.888436,0.879547,0.892712,0.886899,0.005483,4
11,0.067710,0.029463,0.010419,0.007367,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.884536,0.890324,0.890952,0.888603,0.002888,2