In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as matlab

In [2]:
dataset=pd.read_csv("preprocessed_data.csv")
dataset

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes
0,100083,0,0,103500.0,573628.5,24435.0,463500.0,0.009657,-15406,-892,...,0,0,0,0,0,0,0,1,0,0
1,100145,0,1,202500.0,260725.5,16789.5,198000.0,0.018850,-16282,-4375,...,1,0,0,0,0,0,1,0,0,0
2,100165,0,0,175500.0,1293502.5,35568.0,1129500.0,0.018850,-21961,365243,...,0,0,0,0,0,0,1,0,0,0
3,100179,0,0,202500.0,675000.0,53329.5,675000.0,0.031329,-11375,-2311,...,0,0,0,0,1,0,0,0,0,0
4,100190,0,0,162000.0,263686.5,24781.5,238500.0,0.022625,-13972,-4472,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11346,456084,0,1,99000.0,675000.0,21906.0,675000.0,0.020246,-14007,-2021,...,0,0,0,0,0,0,1,0,0,0
11347,456088,1,0,29250.0,663093.0,21519.0,553500.0,0.031329,-20086,365243,...,0,0,0,0,0,0,0,1,0,0
11348,456140,1,1,261000.0,711454.5,47673.0,643500.0,0.018850,-11407,-1641,...,0,0,0,0,0,0,1,0,0,0
11349,456195,0,0,94500.0,270000.0,15075.0,270000.0,0.028663,-20246,-5452,...,0,0,0,0,0,0,0,1,0,0
11350,456226,0,0,225000.0,500566.5,34969.5,472500.0,0.031329,-14106,-226,...,0,0,0,0,0,0,0,0,0,0

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes
0,100083,0,0,103500.0,573628.5,24435.0,463500.0,0.009657,-15406,-892,...,0,0,0,0,0,0,0,1,0,0
1,100145,0,1,202500.0,260725.5,16789.5,198000.0,0.018850,-16282,-4375,...,1,0,0,0,0,0,1,0,0,0
2,100165,0,0,175500.0,1293502.5,35568.0,1129500.0,0.018850,-21961,365243,...,0,0,0,0,0,0,1,0,0,0
3,100179,0,0,202500.0,675000.0,53329.5,675000.0,0.031329,-11375,-2311,...,0,0,0,0,1,0,0,0,0,0
4,100190,0,0,162000.0,263686.5,24781.5,238500.0,0.022625,-13972,-4472,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11346,456084,0,1,99000.0,675000.0,21906.0,675000.0,0.020246,-14007,-2021,...,0,0,0,0,0,0,1,0,0,0
11347,456088,1,0,29250.0,663093.0,21519.0,553500.0,0.031329,-20086,365243,...,0,0,0,0,0,0,0,1,0,0
11348,456140,1,1,261000.0,711454.5,47673.0,643500.0,0.018850,-11407,-1641,...,0,0,0,0,0,0,1,0,0,0
11349,456195,0,0,94500.0,270000.0,15075.0,270000.0,0.028663,-20246,-5452,...,0,0,0,0,0,0,0,1,0,0
11350,456226,0,0,225000.0,500566.5,34969.5,472500.0,0.031329,-14106,-226,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dataset.columns

Index(['SK_ID_CURR', 'TARGET', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       ...
       'FONDKAPREMONT_MODE_reg oper spec account',
       'HOUSETYPE_MODE_specific housing', 'HOUSETYPE_MODE_terraced house',
       'WALLSMATERIAL_MODE_Mixed', 'WALLSMATERIAL_MODE_Monolithic',
       'WALLSMATERIAL_MODE_Others', 'WALLSMATERIAL_MODE_Panel',
       'WALLSMATERIAL_MODE_Stone, brick', 'WALLSMATERIAL_MODE_Wooden',
       'EMERGENCYSTATE_MODE_Yes'],
      dtype='object', length=230)

In [7]:
dataset["TARGET"].value_counts()

0    10666
1      685
Name: TARGET, dtype: int64

In [9]:
independent=dataset[['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'FONDKAPREMONT_MODE_reg oper spec account',
       'HOUSETYPE_MODE_specific housing', 'HOUSETYPE_MODE_terraced house',
       'WALLSMATERIAL_MODE_Mixed', 'WALLSMATERIAL_MODE_Monolithic',
       'WALLSMATERIAL_MODE_Others', 'WALLSMATERIAL_MODE_Panel',
       'WALLSMATERIAL_MODE_Stone, brick', 'WALLSMATERIAL_MODE_Wooden',
       'EMERGENCYSTATE_MODE_Yes']]
independent
dependent=dataset[['TARGET']]

In [10]:
independent.shape

(11351, 19)

In [11]:
dependent

       TARGET
0           0
1           0
2           0
3           0
4           0
...       ...
11346       0
11347       1
11348       1
11349       0
11350       0

[11351 rows x 1 columns]

In [12]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
from sklearn.model_selection import GridSearchCV
param_grid={'solver':['newton-cg','lbfgs','liblinear','saga'],'penalty':['l2']}
grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
#fitting the model for grid search
grid.fit(X_train,Y_train)

C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:   15.6s finished
C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [17]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
re=grid.cv_results_
grid_predictions=grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_pred)

In [20]:
print(cm)

[[3553    0]
 [ 231    0]]

In [21]:
from sklearn.metrics import classification_report
clf_report=classification_report(Y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      3553
           1       0.00      0.00      0.00       231

    accuracy                           0.94      3784
   macro avg       0.47      0.50      0.48      3784
weighted avg       0.88      0.94      0.91      3784

C:\Users\User\Anaconda3\envs\aiml\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.6011833180423105

In [23]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.368435,0.038727,0.016633,0.014009,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.910567,0.911114,0.911114,0.910932,0.000258,1
1,0.224835,0.026529,0.031404,0.012756,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.910567,0.911114,0.911114,0.910932,0.000258,1
2,0.219937,0.051217,0.010416,0.007365,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.910567,0.911114,0.911114,0.910932,0.000258,1
3,0.504558,0.078563,0.006723,0.006863,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.910567,0.911114,0.911114,0.910932,0.000258,1